create table if not exists public.rb_reports (
  id bigint generated by default as identity primary key,
  year integer not null,
  week integer not null,
  block text not null,
  bed text,
  variety text
);

create index if not exists rb_reports_year_week_idx
  on public.rb_reports (year, week);

create index if not exists rb_reports_block_idx
  on public.rb_reports (block);

alter table public.rb_reports enable row level security;

drop policy if exists "Allow public read access to rb_reports" on public.rb_reports;
drop policy if exists "Allow authenticated read access to rb_reports" on public.rb_reports;

create policy "Allow authenticated read access to rb_reports"
on public.rb_reports
for select
to authenticated
using (true);
